### ISSUE TITLE
CPU usage is exceptionally high, reaching up to 1450%

### ISSUE THREAD

**Issue by mhmtbsbyndr** [spider-rs/spider#122]
It's an impressive spider that exhibits remarkable speed. 
However, I've encountered certain domains where the CPU usage is exceptionally high, reaching up to 1450%.

**Comment by mhmtbsbyndr** [comment]
Hi @j-mendez, yes, I am using the "`decentralized`" flag. I can't recall the exact website at the moment because I'm automatically retrieving the URLs of websites using Python and running the command with the URL. I will test it again over the weekend and share the names of the websites that are consuming excessive resources.

**Comment by j-mendez** [comment]
@mhmtbsbyndr got it, going to add the changes to help control back in shortly. I will tag the version with the update once release.

**Comment by j-mendez** [comment]
fixed in v1.31.5 https://github.com/spider-rs/spider/commit/b8caaa0580b9aa0ac4615f3506631f88dfd880d9 .

Reason it was removed was the prior limit was a little too low and some extra logic to add a limit that takes account how many `decentralized` workers you have runnings is needed to allow the speed increase while balancing the CPU at a good place across systems.

**Comment by j-mendez** [comment]
Feel free to re-open if the issue persist. @mhmtbsbyndr
