### ISSUE TITLE
Getting URL after redirect

### ISSUE THREAD

**Issue by joksas** [spider-rs/spider#127]
Thank you for this amazing crate!

I have a quick question and possibly a feature request if it's currently not possible.

Suppose that crawling starts from `https://example.com`, which has a link to `/a`. It seems that if there exists an HTTP redirect from `/a` to `/b`, `page.get_html()` will give the content served at `https://example.com/b`, but `page.get_url()` will return `https://example.com/a`. This might very well be the preferable behavior, but it would also be nice to extract the URL after the redirect, i.e. `https://example.com/b`. Is that possible? Also, it would be great to know when a redirect has occurred.

**Comment by j-mendez** [comment]
Hi @joksas, the default behavior is what it is intended. It is also possible to allow redirects as well, it would take a bit of setting up since we would need to create another data structure include the redirect links or else both of the links would show up in the results. We most likely would want it as a feature flag - something like `keep_redirects`.

**Comment by matteoredaelli** [comment]
I agree it would be useful to return somewhere the "final url". Some libraries have it

  https://github.com/babashka/http-client/issues/41
 
Thanks
Matteo

**Comment by j-mendez** [comment]
@matteoredaelli thank you for the extra details. This is now available in v1.43.0. Use `page.get_url_final` to get the destination. https://github.com/spider-rs/spider/releases/tag/v1.43.0
