### ISSUE TITLE
only let me spider one url

### ISSUE THREAD

**Issue by sebs** [spider-rs/spider#138]
I'd like to use the spider cli to extract the links in or url exactly. no following links. 

thank you for considering. 

S.

**Comment by j-mendez** [comment]
Hi @sebs you can now do this with version `1.45.9`. Example: `spider --domain https://choosealicense.com --budget "*,1" crawl -o`. Thank you for the issue!

**Comment by j-mendez** [comment]
@sebs It may be a lot harder to get some of these features to play with the CLI for expected behavior. It might make sense to use the spider crate to build your custom CLI with [`subscription`] (https://github.com/spider-rs/spider/blob/main/examples/subscribe.rs) sync to easily perform actions per page.

**Comment by sebs** [comment]
So this is where I finally start diving into RUST ? ;)

**Comment by sebs** [comment]
Thanks for the implementation and feedback!
