### ISSUE TITLE
Get a list of images and their alt text

### ISSUE THREAD

**Issue by mgifford** [spider-rs/spider#79]
It seems like I should be able to do some functions of Screaming frog with this. 

What I'm most interested in is:
- a list of images (and all the pages that feature that image), with their alt text (and variations if that isn't consistently used).
- a list of file types (html, pdf, wepb, svg) would also be useful.
- also useful to produce a sitemap.xml file from a crawl.

**Comment by j-mendez** [comment]
Hi @mgifford love the ideas, especially the sitemap option. This project is aligned to just index pages really, and certain capabilities come by default to allow extensions beyond. When getting into network IO and FS IO at this speed we need to add a Semaphore and other lower concepts to intertwine the two at scale in order to build a sitemap and store to disk etc.

I think the first two bullets could work for this project https://github.com/a11ywatch/crawler as it is more aligned for crawling goals like the above.

**Comment by j-mendez** [comment]
Marking closed for out of scope of the crate.
